# Generated by Django 4.2.29 on 2026-05-17 17:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_nom', models.CharField(max_length=200)),
                ('entreprise_adresse', models.TextField(blank=True)),
                ('tuteur_entreprise_nom', models.CharField(max_length=200)),
                ('tuteur_entreprise_email', models.EmailField(max_length=254)),
                ('tuteur_entreprise_telephone', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('mission', models.TextField()),
                ('convention_originale', models.FileField(upload_to='conventions/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Convention signée (PDF)')),
                ('statut', models.CharField(choices=[('attente_tuteur', '📋 En attente tuteur'), ('attente_responsable', '👨\u200d🏫 En attente responsable'), ('attente_service', '📄 En attente service'), ('validee', '✅ Validée'), ('refusee', '❌ Refusée')], default='attente_tuteur', max_length=30)),
                ('commentaire_refus', models.TextField(blank=True)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
