# Generated by Django 4.2.29 on 2026-05-17 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_offrestage_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Lettre de motivation ou message')),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('acceptee', '✅ Acceptée'), ('refusee', '❌ Refusée')], default='en_attente', max_length=20)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.offrestage')),
            ],
            options={
                'ordering': ['-date_candidature'],
                'unique_together': {('etudiant', 'offre')},
            },
        ),
    ]
